### ISSUE TITLE
Rails Backbone Integration

### ISSUE THREAD

**Issue by jon-eng** [jon-eng/bar_roulette_app#4]
## CONTEXT

@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284
##### WHAT USER STORY YOU ARE WORKING ON:

I am working on the user story "As a user, I want to input  starting location, distance, bar price and find a random bar with those parameters"

I am working on the search-parameter branch.
##### WHAT YOU ARE TRYING TO DO:

I am trying to make a call to my api with my search parameters using backbone and rails.
##### DETAILED DESCRIPTION OF THE BUG/ERROR:

I am passing the search parameters from my front end forms to my search route in rails but I am getting a server error.

```
GET http://localhost:3000/venues/explore?near=new%20york&radius=15000&price=2 500 (Internal Server Error)
```

The files involved in my search form are my Bars Controller, Bars Model, routes and my Bars Collection Below is the code for each.

```
Rails.application.routes.draw do
  root 'application#index'
get 'venues/explore' => 'bars#search'
```

```
class BarsController < ApplicationController
  def search
    bar_results = Bar.find_bar(params[:near][:distance][:bar_price])
    render json: bar_results
  end
end
```

```
App.Collections.Bars = Backbone.Collection.extend({

  model: App.Models.Bar,

  searchUrl: function (near, distance, bar_price){
  //api.foursquare.com/v2/venues/explore?ll=40.7,-74&client_id=BNAPSUX5Q2VGUM2JOAQGHXHGCK5WGGHWQPF2VWKZJG5XLKUL&client_secret=F4OSS11HXEOPZP41WPYYXDSV2NHR2BYZGZWNX44OJ3PEBLZ0&v=20150401&section=drinks&limit=5&radius=15000&price=2

  // var near = $('#near').val();
  // var distance = $('#distance').val();
  // var bar_price = $('#bar_price').val();

  return '/venues/explore?near=' + encodeURI(near) + '&radius=' + encodeURI(distance) + '&price=' + encodeURI(bar_price) 
  },

  search: function (near, distance, bar_price){
    $.getJSON(this.searchUrl(near, distance, bar_price))
    .done(this.reset.bind(this))
  }

});
```

```
class Bar

  BASE_URL = "https://api.foursquare.com/v2/venues/explore"

  CLIENT_ID = "BNAPSUX5Q2VGUM2JOAQGHXHGCK5WGGHWQPF2VWKZJG5XLKUL"

  CLIENT_SECRET = "F4OSS11HXEOPZP41WPYYXDSV2NHR2BYZGZWNX44OJ3PEBLZ0"

  V = "20150401"


  def self.find_bar(near, distance, bar_price)
    bar_data = HTTParty.get(BASE_URL, :query =>{:near => near, :client_id => CLIENT_ID, :client_secret => CLIENT_SECRET, :v => V, :section => "drinks", :limit => "200", :radius => distance, :price => bar_price})

    random_bar = bar_data["response"]["groups"][0]["items"].sample

    random_bar
  end


end
```
## WHAT I'VE TRIED

I've tried changing my controllers and routes and backbone forms but to no avail. 
## QUESTION

There are so many moving parts in backbone and rails I'm not too sure how everything is connecting. I know the problem is somewhere either in my endpoint or my model, but I can't seem to pinpoint the problem

:heart:
A meticulous and troubled student

**Comment by WilliamfShaw** [comment]
@jon-eng can you push your most recent code?
